version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/stockulator
    overwrite: yes

permissions:
  - object: /home/ubuntu/stockulator
    owner: root
    group: root
    mode: 755
hooks:
  AfterInstall:
    - location: /script/deploy.sh
      timeout: 60
      runas: root
