version: 0.0
os: linux

files:
  - source: /
    destination: /usr/deploy/stockulator
    overwrite: yes

permissions:
  - object: /usr/deploy/stockulator
    owner: root
    group: root
    mode: 755
hooks:
  AfterInstall:
    - location: deploy.sh
      timeout: 60
      runas: root
