name: 'deploy'

on: push

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18.10.0
      
      - name: Cache node modules
        uses: actions/cache@v2
        id: cache
        with:
          path: node_modules
          key: npm-packages-${{ hashFiles('**/package-lock.json') }}
      
      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm install
      
      - name : Npm Build
        run: CI='false' npm run build
        
      - name: Zip Create
        run: zip -qq -r ./build.zip .
        shell: bash
      
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
          
      - name: Upload to S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.SECRET_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS_KEY }}
        run: |
          aws s3 cp --region ap-northeast-2 ./build.zip s3://stackulator.com/stockulator/build.zip
      
      - name: Deploy
        run: aws deploy create-deployment
          --application-name stackulator-code-deploy
          --deployment-config-name CodeDeployDefault.AllAtOnce
          --deployment-group-name stockulator-dev
          --s3-location bucket=stackulator.com, key=stockulator/build.zip, bundleType=zip
      
