name: 'deploy'

on: push

jobs:
  build:
    name: Build
    runs-on: ubuntu-18.04
    defaults:
      run:
        shell: bash
    
    strategy:
      matrix:
        node-version: '18.10.0'
    
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      
      - name: Cache node modules
        uses: actions/cache@v2
        id: cache
        with:
          path: node_modules
          key: npm-packages-${{ hashFiles('**/package-lock.json') }}
      
      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm install
      
      - name : Npm Build
        run: CI='false' npm run build
        
      - name: Zip Create
        run: zip -qq -r ./build.zip .
        shell: bash
      
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
          
      - name: Upload to S3
        run: aws s3 cp --region ap-northeast-2 ./build.zip s3://stockulatorbucket/stockulator/build.zip
      
      - name: Deploy
        run: aws deploy create-deployment
          --application-name stockulatorcodedeploy
          --deployment-config-name CodeDeployDefault.AllAtOnce
          --deployment-group-name stockulatordeploy
          --s3-location bucket=stockulatorbucket,key=stockulator/build.zip,bundleType=zip
      
