name: 'deploy'

on: push

jobs:
  build:
    name: Build
    runs-on: ubuntu-18.04
    defaults:
      run:
        shell: bash
    
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '12.x'
      
      - name: Cache node modules
        uses: actions/cache@v2
        id: cache
        with:
          path: node_modules
          key: npm-packages-${{ hashFiles('**/package-lock.json') }}
      
      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm install
      
      - name : Npm Build
        run: unset CI && npm run build
      
  docker:
    name: Deploy Docker Image
    runs-on: ubuntu-latest
    needs: build
    steps:
      - run: echo "Github run Id - ${GITHUB_RUN_ID}"
      - uses: actions/checkout@v2
      - name: Retrieve build artifact
        uses: actions/download-artifact@v2
        with:
          name: build-artifact
          path: build
      
      - name: Building Docker Image
        run: docker build --tag ${GITHUB_RUN_ID} .
        
      - name: Docker Hub SignIn
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secret.DOCKER_PASSWORD }}

      - name: Publish Docker Image
        run: docker push ${GITHUB_RUN_ID}
